/ws:
    get:
      summary: WebSocket for real-time speech-to-text
      description: |
        Accepts audio chunks over WebSocket and streams recognized text using Yandex STT gRPC API.

        Audio format:
        - LPCM (LINEAR16_PCM)
        - Sample rate: 8000 Hz
        - Channels: 1 (mono)

        Send messages in JSON:
        - {"bytes": <audio_chunk_bytes>} for audio chunks
        - {"text": "EOS"} to finish streaming

        Responses:
        - {"raw_text": "<recognized_text>"} — final recognized text after end of stream
      responses:
        "101":
          description: WebSocket upgrade
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
              example: "gRPC error or websocket close error"
        "503":
          description: missing API key on server
          content:
            text/plain:
              schema:
                type: string
              example: "API_KEY not found"