name: voice_assistant
description: "Voice assistant module for driver's app with Yandex Alice integration"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.3
  just_audio: ^0.10.4
  path_provider: ^2.1.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/audio/
    - assets/images/alice.png
