version: '3.9'

services:
  userver-service:
    build: userver-backend
    ports:
      - "8080:8080"
  speech-kit-service:
    build: py-backend
    ports:
      - "8081:8081"
    environment:
      - API_KEY=${API_KEY}

  analytics-service:
    build: ../analytics
