version: '3.9'

services:
  userver-service:
    build: .
    ports:
      - "8080:8080"

  analytics-service:
    build: ../analytics

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=voice_assistant
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432"
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d
      - ./.pgdata:/var/lib/postgresql/data
