name: team_42_mobile
description: A Flutter application for Team 42

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  bloc: ^9.0.0
  characters: ^1.4.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  just_audio: ^0.10.4
  provider: ^6.1.5
  alice_voice_player:
    path: packages/alice_voice_player

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/random/
    - assets/audio/

  fonts:
    - family: YandexSansText
      fonts:
        - asset: assets/fonts/YandexSansText-Thin.ttf
          weight: 100
        - asset: assets/fonts/YandexSansText-Light.ttf
          weight: 300
        - asset: assets/fonts/YandexSansText-Regular.ttf
          weight: 400
        - asset: assets/fonts/YandexSansText-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/YandexSansText-Medium.ttf
          weight: 500
        - asset: assets/fonts/YandexSansText-Bold.ttf
          weight: 700
