name: voice_assistant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/random/
  fonts:
    - family: YandexSansText
      fonts:
        - asset: assets/fonts/YandexSansText-Thin.ttf
          weight: 100
        - asset: assets/fonts/YandexSansText-Light.ttf
          weight: 300
        - asset: assets/fonts/YandexSansText-Regular.ttf
          weight: 400
        - asset: assets/fonts/YandexSansText-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/YandexSansText-Medium.ttf
          weight: 500
        - asset: assets/fonts/YandexSansText-Bold.ttf
          weight: 700
