name: voice_assistant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  characters: ^1.4.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  just_audio: ^0.10.4
  provider: ^6.1.5
  alice_voice_player:
    path: packages/alice_voice_player

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/audio/
  fonts:
    - family: YandexSansText
      fonts:
        - asset: assets/fonts/YandexSansText-Thin.ttf
          weight: 100
        - asset: assets/fonts/YandexSansText-Light.ttf
          weight: 300
        - asset: assets/fonts/YandexSansText-Regular.ttf
          weight: 400
        - asset: assets/fonts/YandexSansText-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/YandexSansText-Medium.ttf
          weight: 500
        - asset: assets/fonts/YandexSansText-Bold.ttf
          weight: 700
