worker-threads: 2
worker-fs-threads: 2
logger-level: debug

is-testing: true

server-port: 8080

allowed-url-prefixes:
  - "http://localhost:8083/"
  - "http://localhost:8084/"
  - "http://localhost:8000/"

analytics-url: http://host.docker.internal:8000/cluster
