name: alice_voice_assistant
description: A flexible audio message playback system for Flutter with queue management, priority handling, and real-time amplitude simulation. Perfect for driver apps, notifications, or any organized audio messaging.
version: 0.1.0
homepage: https://github.com/your-org/alice_voice_assistant
repository: https://github.com/your-org/alice_voice_assistant
issue_tracker: https://github.com/your-org/alice_voice_assistant/issues
documentation: https://github.com/your-org/alice_voice_assistant#readme

# Remove this line if you wish to publish to pub.dev
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  test: ^1.24.9

# Configuration for platforms
platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

flutter:
  # Assets for the example app
  assets:
    - assets/audio/
    - assets/images/alice.png

topics:
  - audio
  - voice
  - assistant
  - flutter
  - playback
  - messaging