name: alice_voice_player
description: A pure Dart library for text-to-speech synthesis using Yandex SpeechKit. Provides headless TTS capabilities without UI dependencies.
version: 1.0.0
homepage: https://github.com/your-org/alice_voice_player
repository: https://github.com/your-org/alice_voice_player
issue_tracker: https://github.com/your-org/alice_voice_player/issues
documentation: https://github.com/your-org/alice_voice_player#readme

# Remove this line if you wish to publish to pub.dev
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  crypto: ^3.0.3
  args: ^2.4.2

dev_dependencies:
  test: ^1.24.9
  lints: ^3.0.0

# Configuration for platforms
platforms:
  android:
  ios:
  web:
  windows:
  macos:
  linux:

topics:
  - audio
  - voice
  - tts
  - speech
  - yandex
  - speechkit